version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: db
    ports:
      - 14306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: 123123
    volumes:
      - ./data/mysql:/var/lib/mysql¡
